name: Build and Push to ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: 671336841184.dkr.ecr.us-east-2.amazonaws.com/ecr-iisc-aimlops-cap-fe-streamlite

jobs:
  # -------------------------------
  # 1️⃣ BUILD JOB
  # -------------------------------
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::671336841184:role/iar-github-oidc
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        IMAGE_TAG=latest
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./streamlitapp/basic_app
        docker save $ECR_REPOSITORY:$IMAGE_TAG -o image.tar

    - name: Upload Docker Image as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar

  # -------------------------------
  # 2️⃣ PUSH JOB
  # -------------------------------
  push:
    name: Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download Built Docker Image
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::671336841184:role/iar-github-oidc
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Load and Push Image to ECR
      run: |
        IMAGE_TAG=latest
        docker load -i image.tar
        docker push $ECR_REPOSITORY:$IMAGE_TAG

  # -------------------------------
  # 3️⃣ DEPLOY TRIGGER JOB
  # -------------------------------
  trigger-deploy:
    name: Trigger Deployment Workflow
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Trigger Deploy Workflow Manually
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: "deploy.yml"
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}